How to Run microSWIFT.py in the background:

Enter to following commands into the file /etc/rc.local to run at boot

cd /home/pi/microSWIFT
python3 -u microSWIFT.py >> onboardlog.txt 2>&1 &

* The -u flag makes it so that the print statements are unbuffered and so they do not print to the terminal even when running in the background. 

To view the onboardlog.txt in real time use the command: tail -F onboardlog.txt, to exit from this view use the keyboard shortcut ctrl-c

----------------- GPStoUVZ notes ----------------------
getting the following error on occasion: 

UnboundLocalError: local variable 'gpgga' referenced before assignment
 
- it doesnt happen all the time but it does need to be addressed as a possible failure mode 
- this defintiely needs some checks around it and this error needs to be fixed! 
** This error has been fixed - removed line regarding signal quality check with the GPVTG line since there is no signal quality there

New Error: 
    NonInitialied filename - this was put in as a placeholder and is being removed from the script since it leads to some errors



------------------ SBD notes: --------------------------

installed the termianl program screen using the command: "sudo apt install screen"
this is used to test the modem based on this article: https://learn.adafruit.com/using-the-rockblock-iridium-modem?view=all
to install the rockblock package use the command: "sudo pip3 install adafruit-circuitpython-rockblock"


---------------- Random Notes: --------------------------
installed ipython to test some of the python functionality more onboard rather than within the python interpreter

End of day 08/19/21: microSWIFT.py runs well when you run it manually but it seems to get hung up at the sending function 
                     when you try to run it from boot. This is strange and will need some more experimetnation. We also need to 
                     see where the messages are going that are being sent and how to access them. 
                    '/home/pi/.local/lib/python3.7/site-packages/adafruit_rockblock.py'

--------------- recordGPS Notes -------------------------
We now have the new error that has never occured that looks like this: 

Traceback (most recent call last):
  File "microSWIFT.py", line 92, in <module>
    u, v, z, lat, lon = GPStoUVZ(GPSdataFilename)
  File "/home/pi/microSWIFT/GPS/GPStoUVZ.py", line 26, in GPStoUVZ
    with open(gpsfile, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/microSWIFT/data/microSWIFT025_GPS_20Aug2021_234755UTC.dat'

This is most likely because the GPS is not initializing and I need some more checks within the record GPS function to see why this is happening - It is strange that the GPS wont initialize now
even though it has been consitenstly for weeks.

